language: node_js

node_js:
  - '6'

install:
  - "npm run-script build"

deploy:
  provider: releases
  api_key:
    secure: jEVyaZwi0/mlEoH7xAsh1iHE0wlNYCFOsKGgyDt8YtxHIeyvQxI6cn2RIWM1ljU14cdoJwbj8MbOoSR3/gSiXxLP6e5vkKbj0qZhavF7ff8WoQfy4sD5q92X77G3ZGhOB+jFhQuTAuKv3FUrOGbwhyxnDoe+cGTf5iRINCvVwEnoTGiJKRR9pRDTzBvTzqndJSfddJUX+9MXDtLQZBtSyHd8W2koGJq4P3DytYnQIryTuJ26DhPHlsA0IFWpsBQ1QbgFE3QJ05hU0SsLfS42zVgcKlxWqX6aM4WLdYUTncBCtbmkPo4zXSnLl2NDR+0alzhPyODG8d+zKvIdtKzEqHjncnVXtwC8mnf41oVJ/APLOXKlokZyBqvC98Mg5zMlXqXUMX4ZRSYwwWtbAYD4bHkxxbnaMX0SnEEMnoPqCe5qffRb/HXsieCWJlrICRb11F1qbBN1CKykIYjCheCG6abGkqyG7cPVL5iQbNdqBUgey4PODxugTNBW/oqoF8FmVr41U9tvMyed/5cSQu+pYztCdmMFldEArCBylawnTtQb87PDukVRKCkVwofUWQKFhG0NASZMjHYh72/8fmZgWNdf31R6AK3O2XzjV3abg2x4Bnws1vymr2hgOkFBUbYHTUoj0/DjliKx4ms0xk/Tg5kUjjr1lh9JhVhKXL0YupQ=
  file: dist/index.html
  skip_cleanup: true
  on:
    repo: plusnew/website
