language: node_js

dist: trusty

node_js:
  - node 

sudo: required

before_install:
  - "yarn add coveralls"

script:
  - yarn run test
  - yarn run build

after_success:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

notifications:
  email:
    recipients:
      - travis@plusnew.io
    on_success: change
    on_failure: always

before_deploy:
  - cd dist
  - zip -r website.zip *
  - cd ..

branches:
  only:
    - master

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    repo: plusnew/website

after_deploy:
  - "curl -u $DEPLOY_USER:$DEPLOY_PASSWORD https://www.plusnew.io/checkUpdate.php"
